// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzL20X54c5jlq7brLalkdbNIg5RFYTMK4',
    appId: '1:609371154170:web:f6b72a29796089c1a3cb43',
    messagingSenderId: '609371154170',
    projectId: 'k3register',
    authDomain: 'k3register.firebaseapp.com',
    storageBucket: 'k3register.firebasestorage.app',
    measurementId: 'G-JC73JTMQQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKrL4iAhHzlChCOMlJplc_SV2wHvVehA',
    appId: '1:609371154170:android:478709a28cdb4003a3cb43',
    messagingSenderId: '609371154170',
    projectId: 'k3register',
    storageBucket: 'k3register.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtRhevOON7RxaPAiPWZh06y3LxfYTu3Ss',
    appId: '1:609371154170:ios:e3d7fd07443eb4d9a3cb43',
    messagingSenderId: '609371154170',
    projectId: 'k3register',
    storageBucket: 'k3register.firebasestorage.app',
    iosBundleId: 'com.example.k3register',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtRhevOON7RxaPAiPWZh06y3LxfYTu3Ss',
    appId: '1:609371154170:ios:e3d7fd07443eb4d9a3cb43',
    messagingSenderId: '609371154170',
    projectId: 'k3register',
    storageBucket: 'k3register.firebasestorage.app',
    iosBundleId: 'com.example.k3register',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzL20X54c5jlq7brLalkdbNIg5RFYTMK4',
    appId: '1:609371154170:web:2d173e28c91e08bfa3cb43',
    messagingSenderId: '609371154170',
    projectId: 'k3register',
    authDomain: 'k3register.firebaseapp.com',
    storageBucket: 'k3register.firebasestorage.app',
    measurementId: 'G-WFGD7YZVW4',
  );

}